#pragma once

enum RESOURCE_STATES
{
	RESOURCE_STATE_COMMON = 0,
	RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER = 0x1,
	RESOURCE_STATE_INDEX_BUFFER = 0x2,
	RESOURCE_STATE_RENDER_TARGET = 0x4,
	RESOURCE_STATE_UNORDERED_ACCESS = 0x8,
	RESOURCE_STATE_DEPTH_WRITE = 0x10,
	RESOURCE_STATE_DEPTH_READ = 0x20,
	RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE = 0x40,
	RESOURCE_STATE_PIXEL_SHADER_RESOURCE = 0x80,
	RESOURCE_STATE_STREAM_OUT = 0x100,
	RESOURCE_STATE_INDIRECT_ARGUMENT = 0x200,
	RESOURCE_STATE_COPY_DEST = 0x400,
	RESOURCE_STATE_COPY_SOURCE = 0x800,
	RESOURCE_STATE_RESOLVE_DEST = 0x1000,
	RESOURCE_STATE_RESOLVE_SOURCE = 0x2000,
	RESOURCE_STATE_GENERIC_READ = (((((0x1 | 0x2) | 0x40) | 0x80) | 0x200) | 0x800),
	RESOURCE_STATE_PRESENT = 0,
	RESOURCE_STATE_PREDICATION = 0x200,
	RESOURCE_STATE_VIDEO_DECODE_READ = 0x10000,
	RESOURCE_STATE_VIDEO_DECODE_WRITE = 0x20000,
	RESOURCE_STATE_VIDEO_PROCESS_READ = 0x40000,
	RESOURCE_STATE_VIDEO_PROCESS_WRITE = 0x80000
};